name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install

    - name: Ejecutar pruebas unitarias
      run: npm test

    - name: Notificar a Discord si éxito
      if: ${{ success() }}
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{"content": "✅ Pipeline exitoso para Cristian 🚀"}' \
        https://discord.com/api/webhooks/TU_WEBHOOK_URL

    - name: Notificar a Discord si falla
      if: ${{ failure() }}
      run: |
        curl -H "Content-Type: application/json" \
        -X POST \
        -d '{"content": "❌ Pipeline falló para Cristian 😢"}' \
        https://discord.com/api/webhooks/TU_WEBHOOK_URL